set(_CATKIN_CURRENT_PACKAGE "state_space_example")
set(state_space_example_MAINTAINER "student <student@todo.todo>")
set(state_space_example_DEPRECATED "")
set(state_space_example_VERSION "0.0.0")
set(state_space_example_BUILD_DEPENDS "roscpp" "tf" "visualization_msgs")
set(state_space_example_RUN_DEPENDS "roscpp" "tf" "visualization_msgs")
set(state_space_example_BUILDTOOL_DEPENDS "catkin")