set(_CATKIN_CURRENT_PACKAGE "ugv_course_launch")
set(ugv_course_launch_MAINTAINER "abc <abc@todo.todo>")
set(ugv_course_launch_DEPRECATED "")
set(ugv_course_launch_VERSION "0.0.0")
set(ugv_course_launch_BUILD_DEPENDS )
set(ugv_course_launch_RUN_DEPENDS )
set(ugv_course_launch_BUILDTOOL_DEPENDS "catkin")