// Generated by gencpp from file rl_msgs/RLAction.msg
// DO NOT EDIT!


#ifndef RL_MSGS_MESSAGE_RLACTION_H
#define RL_MSGS_MESSAGE_RLACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_msgs
{
template <class ContainerAllocator>
struct RLAction_
{
  typedef RLAction_<ContainerAllocator> Type;

  RLAction_()
    : action(0)  {
    }
  RLAction_(const ContainerAllocator& _alloc)
    : action(0)  {
  (void)_alloc;
    }



   typedef int32_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::rl_msgs::RLAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_msgs::RLAction_<ContainerAllocator> const> ConstPtr;

}; // struct RLAction_

typedef ::rl_msgs::RLAction_<std::allocator<void> > RLAction;

typedef boost::shared_ptr< ::rl_msgs::RLAction > RLActionPtr;
typedef boost::shared_ptr< ::rl_msgs::RLAction const> RLActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_msgs::RLAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_msgs::RLAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rl_msgs': ['/home/justin/ros_test/src/rl-texplore-ros-pkg-master/src/rl_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rl_msgs::RLAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_msgs::RLAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_msgs::RLAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_msgs::RLAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_msgs::RLAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_msgs::RLAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_msgs::RLAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b028501ac85c840a01d50342b4cc9b6e";
  }

  static const char* value(const ::rl_msgs::RLAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb028501ac85c840aULL;
  static const uint64_t static_value2 = 0x01d50342b4cc9b6eULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_msgs::RLAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_msgs/RLAction";
  }

  static const char* value(const ::rl_msgs::RLAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_msgs::RLAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for describing an action in RL\n\
\n\
int32 action\n\
";
  }

  static const char* value(const ::rl_msgs::RLAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_msgs::RLAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_msgs::RLAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_msgs::RLAction_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_MSGS_MESSAGE_RLACTION_H
