// Generated by gencpp from file rl_msgs/RLExperimentInfo.msg
// DO NOT EDIT!


#ifndef RL_MSGS_MESSAGE_RLEXPERIMENTINFO_H
#define RL_MSGS_MESSAGE_RLEXPERIMENTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_msgs
{
template <class ContainerAllocator>
struct RLExperimentInfo_
{
  typedef RLExperimentInfo_<ContainerAllocator> Type;

  RLExperimentInfo_()
    : episode_number(0)
    , episode_reward(0.0)
    , number_actions(0)  {
    }
  RLExperimentInfo_(const ContainerAllocator& _alloc)
    : episode_number(0)
    , episode_reward(0.0)
    , number_actions(0)  {
  (void)_alloc;
    }



   typedef int32_t _episode_number_type;
  _episode_number_type episode_number;

   typedef float _episode_reward_type;
  _episode_reward_type episode_reward;

   typedef int32_t _number_actions_type;
  _number_actions_type number_actions;





  typedef boost::shared_ptr< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RLExperimentInfo_

typedef ::rl_msgs::RLExperimentInfo_<std::allocator<void> > RLExperimentInfo;

typedef boost::shared_ptr< ::rl_msgs::RLExperimentInfo > RLExperimentInfoPtr;
typedef boost::shared_ptr< ::rl_msgs::RLExperimentInfo const> RLExperimentInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_msgs::RLExperimentInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rl_msgs': ['/home/justin/ros_test/src/rl-texplore-ros-pkg-master/src/rl_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df389dab0f017dc2a66e6cedd44b7a1e";
  }

  static const char* value(const ::rl_msgs::RLExperimentInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf389dab0f017dc2ULL;
  static const uint64_t static_value2 = 0xa66e6cedd44b7a1eULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_msgs/RLExperimentInfo";
  }

  static const char* value(const ::rl_msgs::RLExperimentInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message displaying / plotting / printing info about experiments\n\
\n\
int32 episode_number\n\
float32 episode_reward\n\
\n\
int32 number_actions\n\
";
  }

  static const char* value(const ::rl_msgs::RLExperimentInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.episode_number);
      stream.next(m.episode_reward);
      stream.next(m.number_actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLExperimentInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_msgs::RLExperimentInfo_<ContainerAllocator>& v)
  {
    s << indent << "episode_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.episode_number);
    s << indent << "episode_reward: ";
    Printer<float>::stream(s, indent + "  ", v.episode_reward);
    s << indent << "number_actions: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_actions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_MSGS_MESSAGE_RLEXPERIMENTINFO_H
