set(_CATKIN_CURRENT_PACKAGE "ugv_course_gazebo")
set(ugv_course_gazebo_MAINTAINER "abc <abc@todo.todo>")
set(ugv_course_gazebo_DEPRECATED "")
set(ugv_course_gazebo_VERSION "0.0.0")
set(ugv_course_gazebo_BUILD_DEPENDS )
set(ugv_course_gazebo_RUN_DEPENDS )
set(ugv_course_gazebo_BUILDTOOL_DEPENDS "catkin")