set(_CATKIN_CURRENT_PACKAGE "hector_example")
set(hector_example_MAINTAINER "abc <abc@todo.todo>")
set(hector_example_DEPRECATED "")
set(hector_example_VERSION "0.0.0")
set(hector_example_BUILD_DEPENDS )
set(hector_example_RUN_DEPENDS )
set(hector_example_BUILDTOOL_DEPENDS "catkin")