set(_CATKIN_CURRENT_PACKAGE "robot_sensors")
set(robot_sensors_MAINTAINER "abc <abc@todo.todo>")
set(robot_sensors_DEPRECATED "")
set(robot_sensors_VERSION "0.0.0")
set(robot_sensors_BUILD_DEPENDS )
set(robot_sensors_RUN_DEPENDS )
set(robot_sensors_BUILDTOOL_DEPENDS "catkin")