set(_CATKIN_CURRENT_PACKAGE "roundbot_control")
set(roundbot_control_MAINTAINER "micho <micho@todo.todo>")
set(roundbot_control_DEPRECATED "")
set(roundbot_control_VERSION "0.0.0")
set(roundbot_control_BUILD_DEPENDS "controller_interface")
set(roundbot_control_RUN_DEPENDS "controller_interface" "roscpp")
set(roundbot_control_BUILDTOOL_DEPENDS "catkin" "roscpp")